
##
## Build
##

FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go ./
COPY .env ./

RUN go build -o /_0_data_collection

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /_0_data_collection /_0_data_collection

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/_0_data_collection"]