class_stats = {
    "Beast": [31, 35, 31, 43],
    "Aquatic": [39, 39, 35, 27],
    "Plant": [43, 31, 31, 35],
    "Bird": [27, 43, 35, 35],
    "Bug": [35, 31, 35, 39],
    "Reptile": [39, 35, 31, 35],
    "Dusk": [43, 39, 27, 31],
    "Mech": [31, 39, 43, 27],
    "Dawn": [35, 35, 39, 31],
}
part_stats = {
    "Beast": [0, 1, 0, 3],
    "Aquatic": [1, 3, 0, 0],
    "Plant": [3, 0, 0, 1],
    "Bird": [0, 3, 0, 1],
    "Bug": [1, 0, 0, 3],
    "Reptile": [3, 1, 0, 0],
}


def engineer_combos(df):
    df = df.copy()
    df.loc[:, "Back-Mouth"] = df["Back"] + "/" + df["Mouth"]
    df.loc[:, "Back-Horn"] = df["Back"] + "/" + df["Horn"]
    df.loc[:, "Back-Tail"] = df["Back"] + "/" + df["Tail"]
    df.loc[:, "Mouth-Horn"] = df["Mouth"] + "/" + df["Horn"]
    df.loc[:, "Mouth-Tail"] = df["Mouth"] + "/" + df["Tail"]
    df.loc[:, "Horn-Tail"] = df["Horn"] + "/" + df["Tail"]
    df.loc[:, "Back-Mouth-Horn"] = df["Back"] + "/" + df["Mouth"] + "/" + df["Horn"]
    df.loc[:, "Back-Mouth-Tail"] = df["Back"] + "/" + df["Mouth"] + "/" + df["Tail"]
    df.loc[:, "Back-Horn-Tail"] = df["Back"] + "/" + df["Horn"] + "/" + df["Tail"]
    df.loc[:, "Mouth-Horn-Tail"] = df["Mouth"] + "/" + df["Horn"] + "/" + df["Tail"]
    df.loc[:, "Build"] = (
        df["Back"] + "/" + df["Mouth"] + "/" + df["Horn"] + "/" + df["Tail"]
    )
    return df


combos = [
    "Back-Mouth",
    "Back-Horn",
    "Back-Tail",
    "Mouth-Horn",
    "Mouth-Tail",
    "Horn-Tail",
]
tricombos = ["Back-Mouth-Horn", "Back-Mouth-Tail", "Back-Horn-Tail", "Mouth-Horn-Tail"]
build = ["Build"]

card_scores = {
    **dict.fromkeys(
        [
            "Pigeon Post",
            "Tri Spikes",
            "Bidens",
            "Post Fight",
            "Croc",
            "Bone Sail",
            "Fish Snack",
            "Arco",
            "Perch",
            "Incisor",
            "Mint",
            "Cerastes",
            "Wall Gecko",
            "Caterpillars",
            "Snail Shell",
            "Shoal Star",
            "Hermit",
            "Tiny Turtle",
            "Peace Maker",
            "Eggshell",
            "Goda",
            "Catfish",
            "Sponge",
            "Goldfish",
        ],
        1,
    ),
    **dict.fromkeys(
        [
            "Serious",
            "Red Ear",
            "Beech",
            "Zigzag",
            "Mosquito",
            "Thorny Caterpillar",
            "Lam",
            "Hot Butt",
            "Hatsune",
            "Watermelon",
            "Sandal",
            "Buzz Buzz",
            "Granma's Fan",
            "Feather Spear",
            "Jaguar",
            "Navaga",
            "Ranchu",
            "Tadpole",
            "Hare",
            "Balloon",
            "Pocky",
            "Anemone",
            "Pliers",
            "Dual Blade",
            "Shiba",
            "Gila",
            "Doubletalk",
            "Teal Shell",
            "Scarab",
            "Cactus",
            "Swallow",
            "Nut Cracker",
            "Iguana",
            "Scaly Spoon",
            "Scaly Spear",
            "Potato Leaf",
            "Carrot",
            "Herbivore",
            "Bamboo Shoot",
            "Pumpkin",
            "Cute Bunny",
            "Parasite",
            "Garish Worm",
            "Cloud",
            "Hungry Bird",
            "Kestrel",
            "Trump",
            "Raven",
            "Cupid",
            "Merry",
            "Little Branch",
            "Timber",
            "Risky Beast",
            "Piranha",
            "Oranda",
            "Clamshell",
            "Babylonia",
            "Blue Moon",
            "Feather Fan",
            "Nimo",
        ],
        0.5,
    ),
    **dict.fromkeys(
        [
            "Little Owl",
            "Tri Feather",
            "Rice",
            "Confident",
            "Ronin",
            "Razor Bite",
            "Kotaro",
            "Toothless Bite",
            "Rose Bud",
            "Shiitake",
            "Turnip",
            "Leaf Bug",
            "Antenna",
            "Lagging",
            "Wing Horn",
            "Gerbil",
            "Shrimp",
            "Koi",
            "Risky Fish",
            "Axie Kiss",
            "Imp",
        ],
        0.0,
    ),
    **dict.fromkeys(
        [
            "Indian Star",
            "Kingfisher",
            "Furball",
            "Bumpy",
            "Watering Can",
            "Grass Snake",
            "Cuckoo",
            "Cottontail",
            "Tiny Dino",
            "Unko",
            "Ant",
            "Spiky Wing",
            "Silence Whisper",
        ],
        -0.5,
    ),
    **dict.fromkeys(
        [
            "The Last One",
            "Cattail",
            "Pupae",
            "Hero",
            "Green Thorns",
            "Square Teeth",
            "Snake Jar",
            "Yam",
            "Gravel Ant",
            "Twin Tail",
        ],
        -1,
    ),
    **dict.fromkeys(["Pincer", "Strawberry Shortcake"], -2.5),
}

# Attack, Shield, EnergyCost, Stunt, Poison, DmgCombo, Targetting,
# EnergyGain, Buffs/debuffs, CardDraw/Discard, Healing/Shielding/Blocking
card_attributes = {
    "Hermit": [0, 115, 1, 0, 0, 0, 0, 0, 0, 0, 1],
    "Blue Moon": [120, 30, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    "Goldfish": [110, 20, 1, 0, 0, 0, 0, 0, 1, 0, 0],
    "Sponge": [60, 90, 1, 0, 0, 0, 0, 0, 1, 0, 0],
    "Anemone": [80, 40, 1, 0, 0, 0, 0, 0, 0, 0, 1],
    "Perch": [100, 20, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    "Babylonia": [100, 50, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    "Teal Shell": [50, 80, 1, 0, 0, 0, 0, 0, 0, 0, 1],
    "Clamshell": [110, 40, 1, 0, 0, 0, 0, 0, 1, 0, 0],
    "Oranda": [120, 30, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    "Shoal Star": [115, 10, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    "Lam": [110, 40, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    "Catfish": [80, 30, 1, 0, 0, 0, 0, 0, 0, 0, 1],
    "Risky Fish": [110, 30, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    "Piranha": [120, 30, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    "Koi": [110, 30, 1, 0, 0, 0, 0, 0, 1, 0, 0],
    "Nimo": [30, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    "Tadpole": [110, 40, 1, 0, 0, 0, 0, 0, 1, 0, 0],
    "Ranchu": [120, 30, 1, 0, 0, 0, 0, 0, 1, 0, 0],
    "Navaga": [100, 40, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    "Shrimp": [30, 30, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    "Ronin": [75, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    "Hero": [60, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    "Jaguar": [115, 40, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    "Navaga": [100, 40, 1, 0, 0, 1, 0, 0, 0, 0, 0],
}
